force-app/main/default/objects/FW_Service_Setting__mdt/FW_Service_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Service Settings</description>
    <label>FW Service Setting</label>
    <pluralLabel>FW Service Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/Compressed__c.field-meta.xml
<CustomField>
    <fullName>Compressed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Compressed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/CustomCredential__c.field-meta.xml
<CustomField>
    <fullName>CustomCredential__c</fullName>
    <label>Custom Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Service Endpoint</description>
    <label>Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/EndpointParameters__c.field-meta.xml
<CustomField>
    <fullName>EndpointParameters__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Endpoint Parameters</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/HeaderName__c.field-meta.xml
<CustomField>
    <fullName>HeaderName__c</fullName>
    <label>Header Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/InputClass__c.field-meta.xml
<CustomField>
    <fullName>InputClass__c</fullName>
    <label>Input Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/LogRequest__c.field-meta.xml
<CustomField>
    <fullName>LogRequest__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Log Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/LogResponse__c.field-meta.xml
<CustomField>
    <fullName>LogResponse__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Log Response</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/LogStatus__c.field-meta.xml
<CustomField>
    <fullName>LogStatus__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Log Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/LogWithCallout__c.field-meta.xml
<CustomField>
    <fullName>LogWithCallout__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Log With Callout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/OutputClass__c.field-meta.xml
<CustomField>
    <fullName>OutputClass__c</fullName>
    <label>Output Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/ProcessingClass__c.field-meta.xml
<CustomField>
    <fullName>ProcessingClass__c</fullName>
    <label>Processing Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <defaultValue>30000</defaultValue>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FW_ServiceIO.cls
public without sharing class FW_ServiceIO {

    public class NameException extends Exception {}

    public static final map <String, FW_ServiceIO_Interface> strategies;

    private FW_ServiceIO_Interface strategy;

    static {

        system.debug('ServiceIO - Static variables');

        List <FW_Service_Setting__mdt> serviceSettings = [Select 
                                                                Timeout__c, Strategy__c, QualifiedApiName, ProcessingClass__c, OutputClass__c, Operation__c,  
                                                                MasterLabel, LogWithCallout__c, LogStatus__c, LogResponse__c, LogRequest__c, Label, InputClass__c, 
                                                                Id, HeaderName__c, EndPoint__c, EndPointParameters__c, DeveloperName, Compressed__c, 
                                                                NamedCredential__c, CustomCredential__c
                                                                //Certificate__c, CertificatePassword__c, CertificateName__c 
                                                                    From FW_Service_Setting__mdt];

        List<String> strategyNames = new List<String> ();

        for (FW_Service_Setting__mdt ss: serviceSettings) {
            strategyNames.add(ss.ProcessingClass__c);
        }

        strategies = new Map<String, FW_ServiceIO_Interface> ();

        for (String name: strategyNames) {
            system.debug('@@ProcessingClass' + name);
            try {

                strategies.put(name, (FW_ServiceIO_Interface) Type.forName(name).newInstance());
            } catch (Exception e) {
                system.debug('Strategy Exception : ' + e.getMessage() + e.getStackTraceString());
                continue;
            }
        }
    }

    public FW_ServiceIO(String ioClass) {

        system.debug('ServiceIO - Constructor');
        if (!strategies.containsKey(ioClass))
            throw new NameException(ioClass);
        strategy = strategies.get(ioClass);

    }

    public Object convertInputToRequest(object serviceInput, FW_Service_Settings serviceSettings, FW_Service_Details serviceDetails) {
        system.debug('ServiceIO - convertInputToRequest');
        return strategy.convertInputToRequest(serviceInput, serviceSettings, serviceDetails);
    }

    public Object invokeWebserviceCallout(FW_Service_SOAPRequest soapRequest) {
        system.debug('ServiceIO - invokeWebserviceCallout');
        return strategy.invokeWebserviceCallout(soapRequest);
    }
    
    public Object invokeWebserviceAsyncCallout(Continuation continuation, FW_Service_SOAPRequest soapRequest) {
        system.debug('ServiceIO - invokeWebserviceAsyncCallout');
        return strategy.invokeWebserviceAsyncCallout(continuation, soapRequest);
    }
    
    public Object processContinuationResponse(object continuationOutput) {
        system.debug('ServiceIO - processContinuationResponse');
        return strategy.processContinuationResponse(continuationOutput);
    }

    public Object convertResponseToOutput(object request, object response, map<string, string> responseHeader, FW_Service_Status serviceStatus) {
        system.debug('ServiceIO - convertResponseToOutput');
        return strategy.convertResponseToOutput(request, response, responseHeader, serviceStatus);
    }

    public Object prepareMockOutput(object request, object response, map<string, string> responseHeader, FW_Service_Status serviceStatus) {
        system.debug('ServiceIO - convertResponseToOutput');
        return strategy.prepareMockOutput(request, response, responseHeader, serviceStatus);
    }

}