force-app/main/default/objects/FW_TransformationSetting__mdt/FW_TransformationSetting__mdt.object-meta.xml
<CustomObject>
    <description>Transformation Settings</description>
    <label>FW Transformation Setting</label>
    <pluralLabel>FW Transformation Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FW_TransformationSetting__mdt/fields/LogAdmin__c.field-meta.xml
<CustomField>
    <fullName>LogAdmin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_TransformationSetting__mdt/fields/LogFail__c.field-meta.xml
<CustomField>
    <fullName>LogFail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log Fail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_TransformationSetting__mdt/fields/LogInput__c.field-meta.xml
<CustomField>
    <fullName>LogInput__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log Input</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_TransformationSetting__mdt/fields/LogInputPII__c.field-meta.xml
<CustomField>
    <fullName>LogInputPII__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log Input PII (No PII)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_TransformationSetting__mdt/fields/LogOutput__c.field-meta.xml
<CustomField>
    <fullName>LogOutput__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log Output</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_TransformationSetting__mdt/fields/LogOutputPII__c.field-meta.xml
<CustomField>
    <fullName>LogOutputPII__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log Output PII (No PII)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_TransformationSetting__mdt/fields/LogStatus__c.field-meta.xml
<CustomField>
    <fullName>LogStatus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_TransformationSetting__mdt/fields/LogWithCallout__c.field-meta.xml
<CustomField>
    <fullName>LogWithCallout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log With Callout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_TransformationSetting__mdt/fields/ServiceContinuation__c.field-meta.xml
<CustomField>
    <fullName>ServiceContinuation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Continuation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_TransformationSetting__mdt/fields/ServiceContinuationMethod__c.field-meta.xml
<CustomField>
    <fullName>ServiceContinuationMethod__c</fullName>
    <defaultValue>&quot;processResponse&quot;</defaultValue>
    <label>Service Continuation Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_TransformationSetting__mdt/fields/ServiceContinuationTimeout__c.field-meta.xml
<CustomField>
    <fullName>ServiceContinuationTimeout__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Service Continuation Timeout</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FW_TransformationSetting__mdt/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>Service Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FW_Transformation.cls
public with sharing class FW_Transformation {
    
    private FW_TransformationSetting__mdt transformationSetting;    
    public class StrategyNameException extends Exception{}
    public class TransformationException extends Exception{}
    private FW_Transformation_Interface strategy;
    public static final Map<String, FW_Transformation_Interface> strategies;
    
    public Continuation continuation;
    public FW_Service_ContinuationState continuationState;
    
    public boolean isContinuation;
    public Integer continuationTimeout;
    public string continuationMethod;    
    
    static{        
        List<FW_TransformationSetting__mdt> transformationSettings = [Select 
                                                                        InputClass__c, OutputClass__c, ProcessingClass__c, ServiceContinuation__c, ServiceName__c
                                                                            From FW_TransformationSetting__mdt];      
        List<String> strategyNames = new List<String>();
        
        for(FW_TransformationSetting__mdt ts : transformationSettings){          
            strategyNames.add(ts.ProcessingClass__c);
        }
        strategies = new Map<String, FW_Transformation_Interface>();
        
        for(String name : strategyNames){
            try{
            	strategies.put(name, (FW_Transformation_Interface)Type.forName(name).newInstance());                    
            }
            catch(Exception e){
              system.debug('Transformation Strategy Exception : ' + e.getMessage());              
                continue;
            }
        }
    }   
    
    public FW_Transformation(String transformationName){
        transformationSetting = [Select 
                                QualifiedApiName, ProcessingClass__c, ServiceContinuation__c, ServiceName__c,
                                InputClass__c, OutputClass__c, LogFail__c, LogAdmin__c,
                                LogInput__c, LogOutput__c, LogStatus__c, LogWithCallout__c,
                                ServiceContinuationTimeout__c, ServiceContinuationMethod__c,
                                LogInputPII__c, LogOutputPII__c
                                    From FW_TransformationSetting__mdt
                                        WHERE QualifiedApiName =: transformationName
                                            limit 1];
        if(transformationSetting != null){
            if(!strategies.containsKey(transformationSetting.ProcessingClass__c))
                throw new StrategyNameException(transformationSetting.ProcessingClass__c);
            strategy = strategies.get(transformationSetting.ProcessingClass__c);
          
            isContinuation = transformationSetting.ServiceContinuation__c;
            continuationTimeout = Integer.ValueOf(transformationSetting.ServiceContinuationTimeout__c);
            continuationMethod = transformationSetting.ServiceContinuationMethod__c;
        }
        else
          throw new TransformationException('Error : Transformation Configuration Setup is Missing for : ' + transformationName);          
    }    
    
    public object execute(object dataInput){
        
        FW_Transformation_Settings otherSettings = new FW_Transformation_Settings();
        otherSettings.continuation = continuation;
        otherSettings.continuationState = continuationState;
        
        system.debug('Data Input : '+ dataInput);
        
        return strategy.transformAndExecute(transformationSetting, dataInput, otherSettings);
    }
    
    public object transformContinuationOutput(object continuationOutput){
        
        FW_Transformation_Settings otherSettings = new FW_Transformation_Settings();
        otherSettings.continuationState = continuationState;
        
        return strategy.transformContinuationOutput(transformationSetting, continuationOutput, otherSettings);
    }
    
}