force-app/main/default/objects/FW_Service_Status_Log__c/FW_Service_Status_Log__c.object-meta.xml
<CustomObject>
    <description>Service Status Logs</description>
    <label>FW Service Status Log</label>
    <nameField>
        <label>Status Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FW Service Status Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FW_Service_Status_Log__c/fields/ErrorCode__c.field-meta.xml
<CustomField>
    <fullName>ErrorCode__c</fullName>
    <description>Error Code</description>
    <label>Error Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Status_Log__c/fields/ErrorDescription__c.field-meta.xml
<CustomField>
    <fullName>ErrorDescription__c</fullName>
    <description>Error Description</description>
    <label>Error Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FW_Service_Status_Log__c/fields/MessageReference__c.field-meta.xml
<CustomField>
    <fullName>MessageReference__c</fullName>
    <externalId>true</externalId>
    <label>Message Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FW_Service_StatusServiceTest.cls
@isTest
public without sharing class FW_Service_StatusServiceTest {
    
    static testMethod void PositiveTest() { 
        FW_Service_Status_Log__c fss = new FW_Service_Status_Log__c();
        fss.Name = 'Test';
        fss.MessageReference__c = '500';       
        fss.ErrorCode__c = 'E';
        fss.ErrorDescription__c = 'Error';
        insert fss;
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        string JsonMsg = '{"key": "Value"}';
        req.requestURI = '/services/apexrest/DemoUrl';  //Request URL
        req.httpMethod = 'POST';//HTTP Request Type
        req.requestBody = Blob.valueof(JsonMsg);
        RestContext.request = req;
        RestContext.response= res;    
         FW_Service_Status_Log__c  response = FW_Service_StatusService.doGet();
    }
    
}