force-app/main/default/objects/FW_Global_Setting__mdt/FW_Global_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Global Settings</description>
    <label>FW Global Setting</label>
    <pluralLabel>FW Global Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FW_Service_Setting__mdt/FW_Service_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Service Settings</description>
    <label>FW Service Setting</label>
    <pluralLabel>FW Service Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/Compressed__c.field-meta.xml
<CustomField>
    <fullName>Compressed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Compressed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/CustomCredential__c.field-meta.xml
<CustomField>
    <fullName>CustomCredential__c</fullName>
    <label>Custom Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Service Endpoint</description>
    <label>Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/EndpointParameters__c.field-meta.xml
<CustomField>
    <fullName>EndpointParameters__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Endpoint Parameters</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/HeaderName__c.field-meta.xml
<CustomField>
    <fullName>HeaderName__c</fullName>
    <label>Header Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/InputClass__c.field-meta.xml
<CustomField>
    <fullName>InputClass__c</fullName>
    <label>Input Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/LogRequest__c.field-meta.xml
<CustomField>
    <fullName>LogRequest__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Log Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/LogRequestPII__c.field-meta.xml
<CustomField>
    <fullName>LogRequestPII__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log Request PII (No PII)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/LogResponse__c.field-meta.xml
<CustomField>
    <fullName>LogResponse__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Log Response</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/LogResponsePII__c.field-meta.xml
<CustomField>
    <fullName>LogResponsePII__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Log Response PII (No PII)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/LogStatus__c.field-meta.xml
<CustomField>
    <fullName>LogStatus__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Log Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/LogWithCallout__c.field-meta.xml
<CustomField>
    <fullName>LogWithCallout__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Log With Callout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/MockResponse__c.field-meta.xml
<CustomField>
    <fullName>MockResponse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mock Response</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/OutputClass__c.field-meta.xml
<CustomField>
    <fullName>OutputClass__c</fullName>
    <label>Output Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/ProcessingClass__c.field-meta.xml
<CustomField>
    <fullName>ProcessingClass__c</fullName>
    <label>Processing Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <label>Strategy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FW_Service_Setting__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <defaultValue>30000</defaultValue>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FW_Service.cls
public with sharing class FW_Service {
    
    private FW_Service_Setting__mdt serviceSetting;
    public Continuation continuation;
    public FW_Service_ContinuationState continuationState;
    public FW_Service_Details serviceDetails;
    
    public class StrategyNameException extends Exception{}
    
    public class ServiceSettingException extends Exception{}
    
    private FW_Service_Interface strategy;    
    
    public static final Map<String, FW_Service_Interface> strategies;    
    
    static{
        
        system.debug('SERVICE - static variables');
        try {
                FW_Global_Setting__mdt serviceStrategies = [Select 
                                                                QualifiedApiName, MasterLabel, Label, Id, DeveloperName, Value__c
                                                                    From FW_Global_Setting__mdt 
                                                                        where QualifiedApiName = : FW_Service_Helper.serviceStrategies 
                                                                            limit 1];
             List<String> strategyNames = new List<String>();
    
            if(serviceStrategies != null && serviceStrategies.Value__c != null)
                strategyNames = serviceStrategies.Value__c.split(',');
                
            strategies = new Map<String, FW_Service_Interface>();
            
            for(String name : strategyNames){
                try{
                    strategies.put(name, (FW_Service_Interface)Type.forName(name).newInstance());                    
                }
                catch(Exception e){
                  system.debug('Service Strategy Exception : ' + e.getMessage());
                    continue;
                }
            }
        } catch(Exception ex) {
            //GEMS_CreateExceptionLog.insertErrorLog(ex, null, null, null, 'FW_Service', 'Case', null, 'FW_Service.staticBlock','High');             
        }
    }   
    
    public FW_Service(String serviceName){
        
        system.debug('SERVICE - Constructor');
                
        serviceSetting = [Select 
                                Timeout__c, Strategy__c, QualifiedApiName, ProcessingClass__c, OutputClass__c, Operation__c,  
                                MasterLabel, LogWithCallout__c, LogStatus__c, LogResponse__c, LogRequest__c, Label, InputClass__c, 
                                Id, HeaderName__c, EndPoint__c, EndPointParameters__c, DeveloperName, Compressed__c, 
                                LogRequestPII__c, LogResponsePII__c, 
                                MockResponse__c, NamedCredential__c, CustomCredential__c,
                                LogFail__c, LogAdmin__c
                                    From FW_Service_Setting__mdt
                                        WHERE QualifiedApiName =: serviceName
                                            limit 1];

        if(serviceSetting != null){
            
          if(!strategies.containsKey(serviceSetting.Strategy__c))
              throw new StrategyNameException(serviceSetting.Strategy__c);
              
          strategy = strategies.get(serviceSetting.Strategy__c);
          
        }
        else
          throw new ServiceSettingException('Error : Service Configuration Setup is Missing for : ' + serviceName);
          
    }   
    
    public Object callout(Object serviceInput){          
        
        FW_Service_Continuation contSettings = new FW_Service_Continuation();
        contSettings.continuation = continuation;
        contSettings.continuationState = continuationState;
        //contSettings.isContinuation = continuation != null? true : false;
        
        return strategy.performServiceCallout(serviceSetting, serviceInput, contSettings, serviceDetails);        
    }
    
    public Object processResponse(Object continuationOutput){  
        
        FW_Service_Continuation contSettings = new FW_Service_Continuation();
        contSettings.continuationState = continuationState;
        contSettings.isContinuation = false;
        
        return strategy.processContinuationResponse(serviceSetting, continuationOutput, contSettings, serviceDetails);   
    }
    
}